feat: ambigbrenchmark
agential-ai/agential pull request #112
Opened 2024-04-29 00:27 UTC by tedasdf

add prompt example and demo

### 🤔 Reasoning

_Explain the purpose of this PR..._

### 🚧 Changes

_Describe the changes made..._

### ✅ PR Checklist

- [x] Using this PR template?
- [ ] Linked issue?
- [ ] Added feature?
    - [ ] Added/updated docs?
    - [ ] Added/updated tests?

2024-04-29 10:14 UTC, alckasoc requested changes
could you add print statements within the `_prompt_*` functions to print out the `prompt` and the `out`?

2024-04-29 10:14 UTC, alckasoc commented on agential/cog/prompts/react.py
> +Question: When did men's figure skating become a summer Olympic sport?
```suggestion
REACT_AMBIGQA_EXAMPLES = """Question: When did men's figure skating become a summer Olympic sport? 
```

2024-04-29 10:14 UTC, alckasoc commented on agential/cog/prompts/react.py
> +"""
```suggestion
Action 3: Finish[Elizabeth Taylor]"""
```

2024-04-30 23:16 UTC, jsgage7 commented
@tedasdf Prompts and example LGTM. Please update the PR description to be more descriptive and check the boxes, including linking the issue. I see you already completed the to-do boxes on the issue itself, thanks for doing that! Also looks like there are some merge conflicts that need to be resolved.

@alckasoc Just wanted to clarify on the process for the tmp.ipynb. In my previous PR, I created a separate branch so that I could link to the committed notebook without affecting the PR. Not sure if there's a better way to do this, maybe testing it locally and posting screenshots without committing the notebook? But seems like this will be a common thing so it would be good to have best practices on it.

2024-04-30 23:18 UTC, alckasoc commented
hmmmmm

2024-04-30 23:19 UTC, alckasoc commented
yea i guess we could test it locally without committing the nb + maybe upload the nb to slack?

2024-04-30 23:22 UTC, jsgage7 commented
I notice that all messages being sent in this chat are appearing as comments on the PR, I'm going to attach a notebook to this message in slack and see what happens on GH

[Slack File: test.ipynb](https://files.slack.com/files-pri/T06G9G0703E-F071HFXMBT6/test.ipynb)

2024-04-30 23:24 UTC, alckasoc commented
it works! :sunglasses:

2024-04-30 23:29 UTC, jsgage7 commented
Okay so @tedasdf if you could make the changes I mentioned and uncommit the notebook, you should be good to go

2024-04-30 23:38 UTC, tedasdf commented
I uncommit the notebook and resovle the conflict . should i commit merge?

2024-04-30 23:49 UTC, alckasoc approved these changes

2024-04-30 23:49 UTC, merged